### ISSUE TITLE
exchange2016输入正确账号密码域名ip配置提示失败

### ISSUE THREAD

**Issue by santosshen** [openitsystem/itops#1]
如图
![image](https://user-images.githubusercontent.com/25058112/57595819-d9f95700-7579-11e9-87ed-6e75988f9265.png)
系统   2012R2
exchange2016

**Comment by SamGenTLEManKaka** [comment]
在链接邮箱服务器上操作

右键已管理员身份运行powershell，输入以下命令，按Y确认：

`Set-ExecutionPolicy RemoteSigned`

[微软官方说明文档](https://docs.microsoft.com/zh-cn/powershell/exchange/exchange-server/connect-to-exchange-servers-using-remote-powershell?view=exchange-ps)
