### ISSUE TITLE
WSMan设置configuration_name="Microsoft.Exchange"提示404

### ISSUE THREAD

**Issue by XityZhang** [openitsystem/itops#16]
![)9_1MANA2(X(U4W( V$5A5U](https://user-images.githubusercontent.com/62892306/80453419-cb5aaa00-895a-11ea-95dd-7f7a322def18.png)
仿照exapi里远程调用的写法，结果报错
![VRN3FT{~W{UCFWA Y}D0@$O](https://user-images.githubusercontent.com/62892306/80453463-e75e4b80-895a-11ea-91f4-dbc70c70271a.png)
如果path不指定powershell的话，错误变为如下
![NOYXG 6A(2U}24`(PSQTX{9](https://user-images.githubusercontent.com/62892306/80453532-09f06480-895b-11ea-98b2-c83eea535336.png)
请问有没有处理过类似的问题？是我的Exchange配置不正确吗？

**Comment by XityZhang** [comment]
补充一点，我的exchange使用的是2013版本，我在pypsrp的issue里找到了类似的问题
[https://github.com/jborean93/pypsrp/issues/47](url)
怀疑和Exchange版本有关系，我尝试解决一下

**Comment by SamGenTLEManKaka** [comment]
> ![）9_1MANA2（X（U4W（V $ 5A5U](https://user-images.githubusercontent.com/62892306/80453419-cb5aaa00-895a-11ea-95dd-7f7a322def18.png)
> 仿照exapi里远程调用的写法，结果报错 如果路径不指定powershell的话，错误变成如下 请问有没有处理过类似的问题？是我的Exchange配置不正确吗？
> ![VRN3FT {〜W {UCFWA Y} D0 @ $ O](https://user-images.githubusercontent.com/62892306/80453463-e75e4b80-895a-11ea-91f4-dbc70c70271a.png)
> 
> ![NOYXG 6A（2U} 24`（PSQTX {9](https://user-images.githubusercontent.com/62892306/80453532-09f06480-895b-11ea-98b2-c83eea535336.png)

我们一般使用80（http）或443（https）端口来远程exchange powershell。
在exapi源代码中也可以看到
看到你设置的端口号为5985
5985是你更改了exchange的iis端口吗？

**Comment by XityZhang** [comment]
> > ![）9_1MANA2（X（U4W（V $ 5A5U](https://user-images.githubusercontent.com/62892306/80453419-cb5aaa00-895a-11ea-95dd-7f7a322def18.png)
> > 仿照exapi里远程调用的写法，结果报错 如果路径不指定powershell的话，错误变成如下 请问有没有处理过类似的问题？是我的Exchange配置不正确吗？
> > ![VRN3FT {〜W {UCFWA Y} D0 @ $ O](https://user-images.githubusercontent.com/62892306/80453463-e75e4b80-895a-11ea-91f4-dbc70c70271a.png)
> > ![NOYXG 6A（2U} 24`（PSQTX {9](https://user-images.githubusercontent.com/62892306/80453532-09f06480-895b-11ea-98b2-c83eea535336.png)
> 
> 我们一般使用80（http）或443（https）端口来远程exchange powershell。
> 在exapi源代码中也可以看到
> 看到你设置的端口号为5985
> 5985是你更改了exchange的iis端口吗？

我们是80和443提供IIS服务，远程PS用的5985.
现在问题解决了，但是使用方式有些不一样
详细在这：https://github.com/jborean93/pypsrp/issues/47
在pypsrp issue里看到有一些类似的问题，应该是和Exchange版本有关。
