### ISSUE TITLE
页面显示空白

### ISSUE THREAD

**Issue by yong20200808** [openitsystem/itops#18]
配置都顺利完成，登陆域账号没有报错，但是页面显示空白，在chrome开发者工具下提示无法找到
/static/iconfont.css
/static/bigindex/styles.f13d105a8a0b726b47d03fbb25cad893.css
/static/js/bigindex.fe548b47298f4fac40d1.js

**Comment by SamGenTLEManKaka** [comment]
更新修复了这个问题。
手动部署如有问题，可以尝试docker部署

**Comment by SamGenTLEManKaka** [comment]
[修复部分js文件缺失问题](https://github.com/openitsystem/itops/commit/9c87b41228d4d675ee2f29d00036809d4ece9f70)
