### ISSUE TITLE
登录去除谷歌验证

### ISSUE THREAD

**Issue by Greekers** [openitsystem/itops#2]
您好，麻烦问下域用户登录的话，如何去除谷歌验证登录代码，直接使用域账户登录验证登录，谢谢？

**Comment by SamGenTLEManKaka** [comment]
现在验证功能硬编码在代码里，暂时无法配置是否启用。

我们评估下后期是否需要添加此功能，评估后或功能上线后close掉issue

现版本有关谷歌验证登录使用的任何问题，我们可以给予解答或协助处理

徽信群

![image](https://user-images.githubusercontent.com/24671601/58923408-33683680-8772-11e9-8179-bd0331724ccb.png)

**Comment by Centergit** [comment]
[已更新谷歌二次身份验证开关功能](https://github.com/openitsystem/itops/commit/0fe13113a2913e1d7a54e0447a30925994eaab53)
