### ISSUE TITLE
connect to mysql 

### ISSUE THREAD

**Issue by llisvipofbb** [openitsystem/itops#3]
![image](https://user-images.githubusercontent.com/21051009/59003018-f02bc780-8846-11e9-99a8-c8526ceedd37.png)

**Comment by llisvipofbb** [comment]
请问MySQL数据库是怎么连接上的？或者此工程的日志路径在哪里？？

**Comment by Centergit** [comment]
MySQL连接是没有日志记录的。麻烦请确认是否存在此数据库。是否只支持localhost本地访问
现版本有任何配置的问题，我们可以给予解答或协助处理

徽信群
![image](https://user-images.githubusercontent.com/29622638/59168098-e9fb5b00-8b66-11e9-8a0b-d9cf813c452e.png)

**Comment by chengerchao** [comment]
你需要先在mysql创建itops，然后再连接就可以了。
