### ISSUE TITLE
基于vm虚拟机部署

### ISSUE THREAD

**Issue by chengerchao** [openitsystem/itops#5]
Hi:
   我看到5.1 有基于提供的vm虚拟机部署，请问下这个虚拟机从那下载。是否免费？

**Comment by chengerchao** [comment]
请问下这个版本是否有兼容性的问题，我们的系统版本是Windows Server 2012 R2, Exchange版本是Exchange 2016 CU9。我们这边会出现各种个样的 bug，比如说报表偶尔刷新不出来，数据对不上，创建API账号失败

**Comment by wojiaomingxiao** [comment]
您好：
我想问一下，我在虚拟机中部署了您的项目，在 步骤5.1.8. 账号权限配置中 组名定义：AD组属性sAMAccountName中的名称。请问这个sAMAccountName对应的phpLDAPadmin中的各个组的哪个属性值？现在填入一直报错

**Comment by SamGenTLEManKaka** [comment]
> 请问下这个版本是否有兼容性的问题，我们的系统版本是Windows Server 2012 R2，Exchange版本是Exchange 2016 CU9。我们这边会出现各种个样的bug，比如说报表偶尔刷新不出来，数据对不上，创建API账号失败

所有代码基于exchange2010sp3开发，测试
其他exchange版本没有经过测试，但整体功能基本可用。
首页报表从mysql读取，如果是偶尔刷新不出来，问题可能和exchange版本无关，具体可以查看日志页面，看下是否有任何有用信息
首页报表数据基于“报表管理”页面提供的数据，如果数据有误，可以导出excel文件详细对比
--------------------
我们关心后续问题排查进度
可以扫描加入徽新群，一起探讨研究排查问题
![image](https://user-images.githubusercontent.com/24671601/60718787-454b1e00-9f58-11e9-9c98-e2917d0cc9e2.png)

**Comment by santosshen** [comment]
> 嗨：
> 我看到5.1有基于提供的vm虚拟机部署，请问下这个虚拟机从那下载。是否免费？

这个vm虚拟机 ，由于版本，正在快速更新中。就不提供之前的老版本vm虚拟机 ，建议你可以尝试下自己手动部署，很简单的，有什么安装问题，可以在群里，或者git 里面提问

**Comment by santosshen** [comment]
> 您好：
> 我想问一下，我在虚拟机中部署了您的项目，在步骤5.1.8。账号权限配置中组名定义：AD组属性sAMAccountName中的名称。请问这个sAMAccountName对应的phpLDAPadmin中的各个组的哪个属性值？现在填入一直报错

组的属性 sAMAccountName  的值可以在这里找到

![image](https://user-images.githubusercontent.com/25058112/60777986-a1d05800-a167-11e9-93c3-ebec8db4b234.png)

phpLDAPadmin 上面也不会修改这个属性名称的。你可以寻找下

**Comment by santosshen** [comment]
我们使用的 是 python3 的ldap3 
https://github.com/cannatag/ldap3
