### ISSUE TITLE
有虚拟机或docker镜像吗？

### ISSUE THREAD

**Issue by 0x0021** [openitsystem/itops#8]
有虚拟机或docker镜像吗？另外 这个能不能没有exchange的环境下单独管理域控？

**Comment by 0x0021** [comment]
做了个docker镜像，不含mysql，https://hub.docker.com/r/0x0021/itops/tags
`docker run -d -p 80:8080 --name itops --link mysql 0x0021/itops:v1`

**Comment by SamGenTLEManKaka** [comment]
可以在没有exchange的环境下使用。配置页面里可以选择

**Comment by SamGenTLEManKaka** [comment]
docker部署已新增
